name: SwegPoints
main: io.github.willywonka125.swegpoints.SwegPoints
version: 0.2
commands:
  sweg:
    description: "Gives a player a SwegPoint"
    usage: "/sweg [player]"
  nerd:
    description: "Get mak'd."
    usage: "/nerd <player>"
  dick:
    description: "Draws a dick where you're looking"
    usage: "/dick [length]"